name: lint

on:
  push:
    branches:
      - "*"
      - "**/**"
  workflow_dispatch:
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pre-commit checks
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files --hook-stage=manual
